#!/usr/bin/env bash
set -eu

[ -d ~/.cider ] || git clone https://github.com/gtramontina/dotfiles.git ~/.cider
command -v brew   >/dev/null || ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
command -v pip    >/dev/null || brew install python
command -v cider  >/dev/null || pip2 --no-cache-dir install cider

cider restore
