#!/usr/bin/env bash
set -eu

echo "🔧 Running setup scripts…"

path=~/.cider/scripts
self=$(basename "$0")
scripts=$(ls "$path" | grep -v "$self" | sort)

for script_name in $scripts; do
  script_path="$path/$script_name"
  [ -x "$script_path" ] && $script_path
done

echo "✨ All good!"
echo "⚠️ Please reboot"
